name: Android CI

on:
  push:
    paths:
      - '*' 
      - '!*.md'
      - '!*.html'
  pull_request:
    paths:
      - '*' 
      - '!*.html'
      - '!*.md'

jobs:

  build:
    name: Build Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up keystore properties
        run: echo ${{ secrets.KEYSTORE_PROPERY }} | base64 --decode > misc/keystore.properties
      - name: Set up keystore
        run: echo ${{ secrets.KEYSTORE }} | base64 --decode > misc/keystore.jks
      - name: Release build
        run: ./gradlew :app:assembleRelease
        env:
          CI: true
      - name: Upload apk
        uses: actions/upload-artifact@v1.0.0
        with:
          name: yip-release-apk
          path: app/build/outputs/apk/release
      - name: Upload mappings
        uses: actions/upload-artifact@v1.0.0
        with:
          name: yip-mapping
          path: app/build/outputs/mapping/release
      - name: Upload dexcount report
        uses: actions/upload-artifact@v1.0.0
        with:
          name: dexcount-report
          path: app/build/outputs/dexcount

  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1      
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8      
      - name: Test
        run: ./gradlew jacocoTestReportDebug -PdisablePreDex --stacktrace     
      - name: Coverage Report
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
